/**
 * Central icon exports using Iconic Icons (@iconicicons/react).
 * Re-exported with consistent names for app usage.
 */
import {
  SearchIcon as MagnifyingGlassIcon,
  DownloadIcon as ArrowDownTrayIcon,
  PlusIcon,
  TrashIcon,
  SettingsIcon as Cog6ToothIcon,
  ChevronDownIcon,
  HomeIcon,
  SunIcon as LightBulbIcon,
  ClipboardIcon as ListBulletIcon,
  FolderIcon,
  ServerIcon as CircleStackIcon,
  ServerIcon as DatabaseIcon,
  FileTextIcon as DocumentTextIcon,
  CloseIcon as XMarkIcon,
  EyeIcon,
  EyeOffIcon as EyeSlashIcon,
  DashboardIcon as ChartBarSquareIcon,
  TrendingUpIcon as ArrowTrendingUpIcon,
  TableRowsIcon as TableCellsIcon,
  PieChartIcon as DocumentChartBarIcon,
  GridIcon as Square3Stack3DIcon,
  MenuIcon as Menu2Icon,
  LayersIcon as MultipleFoldersIcon,
} from '@iconicicons/react';

export {
  MagnifyingGlassIcon,
  ArrowDownTrayIcon,
  PlusIcon,
  TrashIcon,
  Cog6ToothIcon,
  ChevronDownIcon,
  HomeIcon,
  LightBulbIcon,
  ListBulletIcon,
  FolderIcon,
  CircleStackIcon,
  DatabaseIcon,
  DocumentTextIcon,
  XMarkIcon,
  EyeIcon,
  EyeSlashIcon,
  ChartBarSquareIcon,
  ArrowTrendingUpIcon,
  TableCellsIcon,
  DocumentChartBarIcon,
  Square3Stack3DIcon,
  Menu2Icon,
  MultipleFoldersIcon,
};
