import type { ThemeConfig } from 'antd';
import { theme } from 'antd';
import { designTokens } from './tokens';

const t = designTokens;

export const themeConfig: ThemeConfig = {
  algorithm: theme.darkAlgorithm,

  token: {
    colorPrimary: t.colorPrimary,
    colorSuccess: t.colorSuccess,
    colorWarning: t.colorWarning,
    colorError: t.colorError,
    colorInfo: t.colorInfo,
    colorLink: t.colorLink,
    colorTextBase: t.colorTextBase,
    colorBgBase: t.colorBgBase,
    fontFamily: t.fontFamily,
    fontSize: t.fontSize,
    borderRadius: t.borderRadius,
    colorBgContainer: t.colorBgContainer,
    colorBgElevated: t.colorBgElevated,
    colorText: t.colorText,
    colorTextSecondary: t.colorTextSecondary,
    colorTextTertiary: t.colorTextTertiary,
    colorBorder: t.colorBorder,
    colorBorderSecondary: t.colorBorderSecondary,
    colorTextPlaceholder: t.colorTextPlaceholder,
    colorTextDisabled: t.colorTextDisabled,
    colorPrimaryHover: t.colorPrimaryHover,
    colorPrimaryActive: t.colorPrimaryActive,
    fontSizeSM: t.fontSizeSM,
    fontSizeLG: t.fontSizeLG,
    fontSizeXL: t.fontSizeXL,
    fontSizeHeading1: t.fontSizeHeading1,
    fontSizeHeading2: t.fontSizeHeading2,
    fontSizeHeading3: t.fontSizeHeading3,
    fontSizeHeading4: t.fontSizeHeading4,
    fontSizeHeading5: t.fontSizeHeading5,
    lineHeight: t.lineHeight,
    lineHeightLG: t.lineHeightLG,
    lineHeightSM: t.lineHeightSM,
    lineHeightHeading1: t.lineHeightHeading1,
    lineHeightHeading2: t.lineHeightHeading2,
    lineHeightHeading3: t.lineHeightHeading3,
    lineHeightHeading4: t.lineHeightHeading4,
    lineHeightHeading5: t.lineHeightHeading5,
    fontSizeIcon: t.fontSizeIcon,
    fontWeightStrong: t.fontWeightStrong,
  },

  components: {
    Button: {
      controlHeightSM: t.buttonControlHeightSM,
      controlHeight: t.buttonControlHeight,
      controlHeightLG: t.buttonControlHeightLG,
      contentFontSizeSM: t.buttonContentFontSizeSM,
      contentFontSize: t.buttonContentFontSize,
      contentFontSizeLG: t.buttonContentFontSizeLG,
      contentLineHeightSM: t.buttonContentLineHeightSM,
      contentLineHeight: t.buttonContentLineHeight,
      contentLineHeightLG: t.buttonContentLineHeightLG,
      paddingInlineSM: t.buttonPaddingInlineSM,
      paddingInline: t.buttonPaddingInline,
      paddingInlineLG: t.buttonPaddingInlineLG,
      paddingBlockSM: t.buttonPaddingBlockSM,
      paddingBlock: t.buttonPaddingBlock,
      paddingBlockLG: t.buttonPaddingBlockLG,
      iconGap: t.buttonIconGap,
      borderRadius: t.buttonBorderRadius,
      defaultShadow: t.buttonDefaultShadow,
      primaryShadow: t.buttonPrimaryShadow,
      dangerShadow: t.buttonDangerShadow,
    },
    Input: {
      colorBgContainer: t.inputColorBgContainer,
      controlHeightSM: t.inputControlHeightSM,
      controlHeight: t.inputControlHeight,
      controlHeightLG: t.inputControlHeightLG,
      paddingInlineSM: t.inputPaddingInlineSM,
      paddingInline: t.inputPaddingInline,
      paddingInlineLG: t.inputPaddingInlineLG,
      paddingBlockSM: t.inputPaddingBlockSM,
      paddingBlock: t.inputPaddingBlock,
      paddingBlockLG: t.inputPaddingBlockLG,
      inputFontSizeSM: t.inputFontSizeSM,
      inputFontSize: t.inputFontSize,
      inputFontSizeLG: t.inputFontSizeLG,
      borderRadius: t.inputBorderRadius,
      hoverBorderColor: t.inputHoverBorderColor,
      activeBorderColor: t.inputActiveBorderColor,
      activeShadow: t.inputActiveShadow,
      errorActiveShadow: t.inputErrorActiveShadow,
      colorError: t.inputColorError,
    },
    Select: {
      colorBgContainer: t.inputColorBgContainer,
      controlHeightSM: t.inputControlHeightSM,
      controlHeight: t.inputControlHeight,
      controlHeightLG: t.inputControlHeightLG,
      borderRadius: t.inputBorderRadius,
      hoverBorderColor: t.inputHoverBorderColor,
      activeBorderColor: t.inputActiveBorderColor,
      colorError: t.inputColorError,
    },
    Tabs: {
      itemColor: t.tabsItemColor,
      itemSelectedColor: t.tabsItemSelectedColor,
      itemHoverColor: t.tabsItemHoverColor,
      inkBarColor: t.tabsInkBarColor,
      titleFontSize: t.tabsTitleFontSize,
      titleFontSizeLG: t.tabsTitleFontSizeLG,
    },
  },
};
